# Generated by Django 4.0 on 2022-03-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_new_journalist'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='location',
            field=models.CharField(default='Some Place', max_length=200),
            preserve_default=False,
        ),
    ]
