# Generated by Django 4.0 on 2022-03-22 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_new_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journalist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='new',
            name='journalist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.journalist'),
        ),
        migrations.AlterField(
            model_name='new',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.location'),
        ),
    ]
