# Generated by Django 4.0 on 2022-04-16 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_new_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='category',
        ),
    ]
